CREATE TABLE "USER" (
	"ID"	VARCHAR(40)		NOT NULL,
	"PASSWORD"	VARCHAR2(40)		NULL,
	"NAME"	VARCHAR2(10)		NULL,
	"GENDER"	VARCHAR2(5)		NULL,
	"BIRTH"	DATE		NULL,
	"MAIL"	VARCHAR2(100)		NULL,
	"JOIN_DATE"	DATE		NULL,
	"REG_DATE"	DATE		NULL,
	"UPD_DATE"	VARCHAR(255)		NULL
);

ALTER TABLE "USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY (
	"ID"
);