-- Active: 1709190551102@@127.0.0.1@1521@orcl@HR
-- 66~69 과제

-- 66. 테이블 생성
SELECT *
from MS_USER;

CREATE TABLE MS_USER(
    USER_NO     NUMBER                  NOT NULL PRIMARY KEY,
    USER_ID     VARCHAR2(100)           NOT NULL UNIQUE,
    USER_PW     VARCHAR2(200)           NOT NULL,
    USER_NAME   VARCHAR2(50)            NOT NULL,
    BIRTH       DATE                    NOT NULL,
    TEL         VARCHAR2(20)            NOT NULL UNIQUE,
    ADDRESS     VARCHAR2(200)           NULL,
    REG_DATE    DATE    DEFAULT SYSDATE NOT NULL,
    UPD_DATE    DATE    DEFAULT SYSDATE NOT NULL
);
COMMENT ON TABLE MS_USER IS '커뮤니티 회원의 정보를 관리한다';
COMMENT ON COLUMN MS_USER.USER_NO IS '회원정보';
COMMENT ON COLUMN MS_USER.USER_ID IS '아이디';
COMMENT ON COLUMN MS_USER.USER_PW IS '비밀번호';
COMMENT ON COLUMN MS_USER.USER_NAME IS '이름';
COMMENT ON COLUMN MS_USER.BIRTH IS '생년월일';
COMMENT ON COLUMN MS_USER.TEL IS '전화번호';
COMMENT ON COLUMN MS_USER.ADDRESS IS '주소';
COMMENT ON COLUMN MS_USER.REG_DATE IS '등록일자';
COMMENT ON COLUMN MS_USER.UPD_DATE IS '수정일자';

-- 67. MS_BOARD 테이블을 생성
SELECT *
from MS_BOARD;

CREATE TABLE MS_BOARD(
    BOARD_NO    NUMBER                  NOT NULL PRIMARY KEY,
    TITLE       VARCHAR2(200)           NOT NULL,
    CONTENT     CLOB                    NOT NULL,
    WRITER      VARCHAR2(100)           NOT NULL,
    HIT         NUMBER                  NOT NULL,
    LIKE_CNT    NUMBER                  NOT NULL,
    DEL_YN      CHAR(2)                 NULL,
    DEL_DATE    DATE                    NULL,
    REG_DATE    DATE    DEFAULT SYSDATE NOT NULL,
    UPD_DATE    DATE    DEFAULT SYSDATE NOT NULL
);
COMMENT ON TABLE MS_BOARD IS '커뮤니티 게시판 정보를 관리한다';
COMMENT ON COLUMN MS_BOARD.BOARD_NO IS '글번호';
COMMENT ON COLUMN MS_BOARD.TITLE IS '제목';
COMMENT ON COLUMN MS_BOARD.CONTENT IS '내용';
COMMENT ON COLUMN MS_BOARD.WRITER IS '작성자';
COMMENT ON COLUMN MS_BOARD.HIT IS '조회수';
COMMENT ON COLUMN MS_BOARD.LIKE_CNT IS '좋아요 수';
COMMENT ON COLUMN MS_BOARD.DEL_YN IS '삭제여부';
COMMENT ON COLUMN MS_BOARD.DEL_DATE IS '삭제일자';
COMMENT ON COLUMN MS_BOARD.REG_DATE IS '등록일자';
COMMENT ON COLUMN MS_USER.UPD_DATE IS '수정일자';

-- 68. MS_FILE 테이블을 생성
SELECT *
FROM MS_FILE;
CREATE TABLE MS_FILE(
    FILE_NO     NUMBER                  NOT NULL PRIMARY KEY,
    BOARD_NO    NUMBER                  NOT NULL,
    FILE_NAME   VARCHAR2(2000)          NOT NULL,
    FILE_DATA   BLOB                    NOT NULL,
    REG_DATE    DATE    DEFAULT SYSDATE NOT NULL,
    UPD_DATE    DATE    DEFAULT SYSDATE NOT NULL
);
COMMENT ON TABLE MS_FILE IS '커뮤니티 게시판 첨부파일의 정보를 관리한다';
COMMENT ON COLUMN MS_FILE.FILE_NO IS '파일번호';
COMMENT ON COLUMN MS_FILE.BOARD_NO IS '글번호';
COMMENT ON COLUMN MS_FILE.FILE_NAME IS '파일명';
COMMENT ON COLUMN MS_FILE.FILE_DATA IS '파일';
COMMENT ON COLUMN MS_FILE.REG_DATE IS '등록일자';
COMMENT ON COLUMN MS_FILE.UPD_DATE IS '수정일자';

-- 69. MS_REPLY 테이블을 생성
CREATE TABLE MS_PERLY(
    PERLY_NO    NUMBER                  NOT NULL PRIMARY KEY,
    BOARD_NO    NUMBER                  NOT NULL,
    CONTENT     VARCHAR2(2000)          NOT NULL,
    WRITER      VARCHAR2(100)           NOT NULL,
    DEL_YN      CHAR(2) DEFAULT 'N'     NULL,
    DEL_DATE    DATE                    NULL,
    REG_DATE    DATE    DEFAULT SYSDATE NOT NULL,
    UPD_DATE    DATE    DEFAULT SYSDATE NOT NULL
);
COMMENT ON TABLE MS_PERLY IS '커뮤니티 게시판의 댓글 정보를 관리한다';
COMMENT ON COLUMN MS_PERLY.PERLY_NO IS '댓글번호';
COMMENT ON COLUMN MS_PERLY.BOARD_NO IS '글번호';
COMMENT ON COLUMN MS_PERLY.CONTENT IS '내용';
COMMENT ON COLUMN MS_PERLY.WRITER IS '작성자';
COMMENT ON COLUMN MS_PERLY.DEL_YN IS '삭제여부';
COMMENT ON COLUMN MS_PERLY.DEL_DATE IS '삭제일자';
COMMENT ON COLUMN MS_PERLY.REG_DATE IS '등록일자';
COMMENT ON COLUMN MS_PERLY.UPD_DATE IS '수정일자';